In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([
        [8,8,4],
        [7,9,5],
        [6,10,6],
        [5,12,7]
],columns=["cgpa","profile_score","lpa"]
)

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model=Sequential()
model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

model.summary()

/Users/kristalshrestha/Documents/Code/DeepLearning_practice/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 1.1056443 ,  0.06895244],
        [-0.15333319,  0.2418716 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.26042235],
        [ 1.3856407 ]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights=[
             np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)
            ]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [14]:
model.fit(df.iloc[:,0:-1].values,df["lpa"].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8784  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27.5519
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27.2572
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8983
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.5576
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.1970
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.8094
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.4227
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.0312
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.6485
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.2406
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.8070
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.3865
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.9144
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.4592
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━

In [15]:
model.get_weights()

[array([[0.37361246, 0.37361246],
        [0.36564466, 0.36564466]], dtype=float32),
 array([0.2723189, 0.2723189], dtype=float32),
 array([[0.37293005],
        [0.37293005]], dtype=float32),
 array([0.20486629], dtype=float32)]